server:
  port: 8083
spring:
  application:
    name: service-email
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest
      group-id: email-group
    topic:
      order: order_topic
      payment: payment_topic
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
