server:
  port: 8084
spring:
  application:
    name: service-payment
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest
      group-id: payment-group
    topic:
      order: order_topic
      payment: payment_topic

